using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace E_Ticaret_Proje.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            List<Category> kategoriler = new List<Category>()
            {
                new Category(){ Name = "Edebiyat", Description = "Edebiyat ürünleri"},
                new Category(){ Name = "Kişisel Gelişim", Description = "Kişisel Gelişim ürünleri"},
                new Category(){ Name = "Felsefe", Description = "Felsefe ürünleri"},
                new Category(){ Name = "Bilim", Description = "Bilim ürünleri"},
                new Category(){ Name = "Araştırma-Tarih", Description = "Araştırma-Tarih ürünleri"},
            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();


            List<Author> yazarlar = new List<Author>()
            {
                new Author(){ Name = "İlber Ortaylı", Description = "1947 senesinde Avusturya'da doğdu. 2 yașındayken ailesiyle birlikte Türkiye'ye göç etti. İlk ve orta öğrenimini İstanbul Avusturya Lisesi'nde tamamladı. 1965 yılında Ankara Atatürk Lisesi'nden mezun oldu. Akademik kariyeri 1969 yılında Ankara Üniversitesi Siyasal Bilgiler Fakültesi'ni ve Ankara Üniversitesi Dil, Tarih ve Coğrafya Fakültesi'nin tarih bölümünü bitirdi. Viyana Üniversitesi Slavistik ve Orientalistik Bölümü'nde öğrenim gördü. Yüksek lisans çalışmasını Chicago Üniversitesi'nde Prof. Dr. Halil İnalcık ile yaptı. Ankara Siyasal Bilgiler Fakültesi'nde Tanzimat Sonrası Mahallî İdareler adlı tezi ile 1974 yılında doktor, Osmanlı İmparatorluğu'nda Alman Nüfûzu adlı çalışmasıyla 1979'da doçent oldu. 1982 yılında devletin akademik politikalarına tepki olarak görevinden istifa etti. Bu dönemde Viyana, Berlin, Paris, Princeton, Moskova, Roma, Münih, Strazburg, Yanya, Sofya, Kiel, Cambridge, Oxford ve Tunus üniversitelerinde misafir öğretim üyeliği yaptı, buralarda seminerler ve konferanslar verdi. 1989'da Türkiye'ye dönerek profesör oldu ve 1989-2002 yılları arasında Ankara Üniversitesi Siyasal Bilgiler Fakültesi'nde İdare Tarihi Bilim Dalı Başkanı olarak görev yaptı. Yerli ve yabancı bilimsel dergilerde 16. ile 19. yüzyıllar arası Osmanlı tarihi ve Rus tarihi ile ilgili makaleleri yayınlandı. 2002 yılında Galatasaray Üniversitesi'ne, iki yıl sonra ise Bilkent Üniversitesi'ne konuk öğretim üyesi olarak geçti. Şu anda Galatasaray Üniversitesi Hukuk Fakültesi ve Bilkent Üniversitesi Hukuk Fakültesinde Türk Hukuk Tarihi derslerini vermektedir. Galatasaray Üniversitesi Senato üyesidir. Ayrıca İlke Eğitim ve Sağlık Vakfı Kapadokya Meslek Yüksekokulu Mütevelli Heyeti üyesidir. ..." , Image = "ilber-ortayli.jpg"},
                 new Author(){ Name = "A. M. Celal Şengör", Description = "24 Mart 1955 tarihinde İstanbul'da doğdu. 1973 tarihinde Robert Koleji'ni bitirdikten sonra 1978'de ise State University of New York at Albany'den Jeolog olarak mezun oldu ve aynı üniversiteden 1979'da yüksek lisansını bitirdi. 1981'de İstanbul Teknik Üniversitesi Maden Fakültesi, Genel Jeoloji kürsüsünde asistan olarak görev yapmaya başladı. 1982'de de State University of New York at Albany'den doktora aldı. 1984 yılında Londra Jeoloji Cemiyeti'nin Başkanlık Ödülü'nü, 1986'da TÜBİTAK Bilim Ödülü'nü kazandı. Aynı yıl İstanbul Teknik Üniversitesi Maden Fakültesi Genel Jeoloji Anabilim Dalında doçent oldu. 1988'de Neuchâtel Üniversitesi Fen Fakültesi'nden şeref bilim doktoru unvanına sahip oldu. 1990 yılında Academia Europaea'ya kabul edilden Celal Şengör, aynı yıl Avusturya Jeoloji Servisi muhabir üyesi, 1991 yılında ise Avusturya Jeoloji Derneği şeref üyesi oldu. Yine 1991 yılında Kültür Bakanlığı'nın Bilgi Çağı Ödülünü kazandı. 1992 yılında İstanbul Teknik Üniversitesi Maden Fakültesi Genel Jeoloji Anabilim Dalı'nda profesörlüğe yükseldi. Celal Şengör, ileri seviyede İngilizce, Fransızca ve Almanca bildiğini ifade ederken; Felemenkçe, İtalyanca, Portekizce, İspanyolca ve Osmanlı Türkçesini okuyabildiğini de söylemiştir.", Image = "celal-sengor.jpg" },
                  new Author(){ Name = "Stefan Zweig", Description = "STEFAN ZWEIG, 1881’de Viyana’da doğdu. Avusturya, Fransa ve Almanya’da öğrenim gördü. Savaş karşıtı kişiliğiyle dikkat çekti. 1919-1934 yılları arasında Salzburg’da yaşadı, Nazilerin baskısı yüzünden Salzburg’u terk etmek zorunda kaldı. 1938’de İngiltere’ye, 1939’da New York’a gitti, birkaç ay sonra da Brezilya’ya yerleşti. Önceleri Verlaine, Baudelaire ve Verhaeren çevirileriyle tanındı, ilk şiirlerini ise 1901’de yayımladı. Çok sayıda deneme, öykü, uzun öykünün yanı sıra büyük bir ustalıkla kaleme aldığı yaşamöyküleriyle de ünlüdür. Psikolojiye ve Freud’un öğretisine duyduğu yoğun ilgi, Zweig’ın derin karakter incelemelerinde ifade bulur. Özellikle tarihsel karakterler üzerine yazdığı yorumlar ve yaşamöyküleri, psikolojik çözümlemeler bakımından son derece zengindir. Zweig, Avrupa’nın içine düştüğü siyasi duruma dayanamayarak 1942’de Brezilya’da karısıyla birlikte intihar etti.", Image = "stefan-zweig.jpg"},
                  new Author(){ Name = "Sabahattin Ali", Description = "25 Şubat 1907’de Gümülcine’de doğdu, 2 Nisan 1948’de Kırklareli’nde öldü.1948’de bir yazısı yüzünden tutuklandı, üç ay kadar hapis yattı. Sürekli izlendiği için yurtdışına kaçmak istedi, ancak Kırklareli dolaylarında bir kaçakçı tarafından öldürüldüğü iddia edildi. Şiirler, hikâyeler, romanlar yazdı, çeviriler yaptı.", Image = "sabahattin-ali.jpg"},
                  new Author(){ Name = "George Orwell", Description = "GEORGE ORWELL, 1903’te Hindistan’ın Bengal eyaletinin Montihari kentinde doğdu. Ailesiyle birlikte İngiltere’ye döndükten sonra, öğrenimini Eton College’de tamamladı. Gerçek adı Eric Arthur Blair olan Orwell, 1922-1927 yılları arasında Hindistan İmparatorluk Polisi olarak görev yaptı. Ancak imparatorluk yönetiminin içyüzünü görünce istifa etti. 1950’de yayımladığı Shooting an Elephant (Bir Fili Vurmak) adlı kitabı, sömürge memurlarının davranışlarını eleştiren makalelerin derlemesidir. İkinci Dünya Savaşı’nın sonlarına doğru yazdığı Hayvan Çiftliği, Stalin rejimine karşı sert bir taşlamadır. Orwell’in en çok tanınan yapıtlarından Bin Dokuz Yüz Seksen Dört, bilimkurgu türünün klasik örneklerinden biri olmanın yanı sıra, modern dünyayı protesto eden bir romandır. Burma Günleri ise, Orwell’in Burma’daki (bugünkü Myanmar) İngiliz sömürgeciliğini dile getirdiği ilk kitabıdır. Orwell 1950’de Londra’da öldü.", Image = "george-orwell.jpg"},
                  new Author(){ Name = "Zülfü Livaneli", Description = "Romanları 30 dilde yayımlanan Zülfü Livaneli, 1946 yılında doğdu. 1972 yılında fikirlerinden dolayı askeri cezaevinde yattı, 11 yıl sürgünde yaşadı. Livaneli, 1999 yılında San Remo’da En İyi Besteci ödülüne layık görüldü. Müzik eserleri Londra, Moskova, Berlin, Atina, İzmir Senfoni orkestraları tarafından icra edildi ve Zubin Mehta, Simeon Kogan gibi şeflerce yönetildi.Türkiye dışında Çin Halk Cumhuriyeti, İspanya, Kore ve Almanya’da da çok satanlar arasına giren romanlarıyla, Balkan Edebiyat Ödülü’ne, ABD’de Barnes and Noble Büyük Yazar Ödülü’ne, İtalya ve Fransa’da Yılın Kitabı Ödülü’ne, Türkiye’de ise Yunus Nadi Ödülü’ne ve Orhan Kemal Roman Ödülü’ne layık görüldü. Livaneli, dünya kültür ve barışına yaptığı katkılardan ötürü 1996 yılında Paris’te UNESCO tarafından Büyükelçilikle onurlandırıldı ve Genel Direktör danışmanlığına atandı.2002-2006 yılları arasında TBMM’de ve Avrupa Konseyi’nde milletvekilliği görevinde bulundu.", Image = "zulfu-livaneli.jpg"},
                  new Author(){ Name = "Platon(Eflatun)", Description = "(İÖ 427-348/347) Soylu bir ailenin oğluydu. Sokrates’in ölümüne kadar onun derslerini izledi. Ardından Mısır ve Güney İtalya’yı da kapsayan uzun bir yolculuğa çıktı. İÖ 387’de Atina’ya dönerek Akademia adlı okulu kurdu. Kendisinin olduğu kabul edilen 28 diyalogda, hocası Sokrates’in konuşmalarını bir araya getirir. Bunların en önemlilerinden bazıları şunlardır: Phaidon, Gorgias, Menon, Politikos.", Image = "platon.jpg"},

            };

            foreach (var yazar in yazarlar)
            {
                context.Authors.Add(yazar);
            }
            context.SaveChanges();


            List<Product> urunler = new List<Product>()
            {
                new Product(){ Name = "Bir Ömür Nasıl Yaşanır?", Description = "“Cesur olun. Kendinizi rahat hissettiğiniz alanın dışında pencereler açın. Farklı dünyalarla ancak böyle tanışırsınız. Ben hep yerimde dursaydım, dünyamı değiştirecek insanları aramasaydım, bugün tanıdığınız ben olmazdım. Bir insanın bittiği an, miskinliğe esir olduğu andır. İnsan, konforundan vazgeçmeyi göze almalıdır. Kendi dünyasını yerinden kendisi oynatmalıdır.” İlber Ortaylı, yediden yetmişe herkesin faydalanacağı, bilge şahsiyetinden ve yaşam tecrübesinden süzülen tavsiyelerden oluşan bir eserle karşımızda. İlber Hoca bu kitapta, bir insanın, çocukluktan itibaren hayatın hemen her alanında ihtiyaç duyacağı çözümleri nasıl bulabileceğini örnekler vererek anlatıyor. “Herkes kendi talihinin mimarıdır” sözünü hatırlatarak, kendi yolunu çizmenin ne anlama geldiğini tüm kritik noktalarıyla yorumluyor.- Bir ömrü hakkıyla yaşayabilmek ve yaşanan her andan tat alabilmek için önce ne lazımdır? İnsan hayatı kaç dönemden oluşur ve her bir dönemde neleri tecrübe etmek gerekir? 15, 25, 40 ve 55 yaşları neden birer eşiktir? İnsan kimden, ne öğrenebilir? Kendi kendini yetiştirmek nasıl mümkün olur? Kişi mesleğini neye göre seçmelidir? Bir işin uzmanı olmak ve o uzmanlık bilgisiyle çalışmak için nelere ihtiyaç vardır? Bir dil, en iyi nasıl ve ne zaman öğrenilir? En verimli sonucu alabilmek için nasıl çalışmak gerekir? Sorumluluk sahibi bir insan, kendisi veya çocukları için nasıl bir eğitim modeli aramalıdır? Hayata değer katmak için ne tür insanları arayıp bulmak gerekir? Doğru kararları alabilmek için en çok kimleri dinlemek gerekir? En iyi nasıl seyahat edilir; bir şehir nasıl dolaşılır? Hangi müze, hangi meydan, hangi sokakları görmek için dünyanın bir ucuna kadar gidilebilir? İyi film, güzel müzik, doğru kitap nedir? Hangi temel eserleri dinlemeli, okumalı ve seyretmeliyiz? İnsan yaşadığı şehirden tam manasıyla nasıl yararlanabilir? “Bir Ömür Nasıl Yaşanır?”, ülkemizin medarıiftiharı olmuş bir tarihçinin gözünden, insanın hayattaki anlam arayışına, bu arayışın tadını nasıl çıkaracağına ve süreç boyunca karşılaşacağı zorluklarla nasıl baş etmesi gerektiğine dair çok özel bir kılavuz…", AuthorId = 1, Publisher = "Kronik Kitap", Language = "Türkçe", PageCount = 288, Price = 64.60, Stock = 500, IsApproved = true, CategoryId = 2, Image = "bir-omur-nasil-yasanir.jpg"},
                new Product(){ Name = "İnsan Geleceğini Nasıl Kurar?", Description = "“Bir hedef bulacaksınız, o uğurda çalışacaksınız, hedefinizi gerçekleştirmek için bir yol arayacaksınız, yol yoksa da o yolu yapacaksınız. Bir defa geçtiğiniz yoldan da bir daha geri dönmeyeceksiniz. Çünkü lüzumsuz geri dönüş başarısızlıktır, tekrara düşmektir, ufku kapatmaktır. Hedef bulmak, yol açmak ve aynı yoldan geri dönmemek… Hayattaki gayemiz budur.” İLBER ORTAYLI", AuthorId = 1, Publisher = "Kronik Kitap", Language = "Türkçe", PageCount = 280, Price = 57.00, Stock = 500, IsApproved = true, CategoryId = 2, Image = "insan-gelecegini-nasıl-kurar.jpg"},
                new Product(){ Name = "Gazi Mustafa Kemal Atatürk", Description = "“Tarihin akışını değiştiren, ona mührünü vuran veya büyük tehlikelere mâni olan liderlere her memlekette rastlamak mümkün değildir. Atatürk dünya tarihinin nadiren gördüğü bir dehadır. Birinci Dünya Savaşı'ndan sonra, hiçbir mağlup milletin direniş göstermediği zamanda siviller ve askerlerle dünyaya meydan okumuştur.” İLBER ORTAYLI", AuthorId = 1, Publisher = "Kronik Kitap", Language = "Türkçe", PageCount = 480, Price = 87.00, Stock = 350, IsApproved = true, CategoryId = 2, Image = "Gazi-Mustafa-Kemal-Ataturk.jpg"},
                new Product(){ Name = "Senin Cahilliğin Benim Yaşamımı Etkiliyor", Description = "Senin bilgeliğin bizim yaşamımızı etkiliyor. Fikirlerini samimi olarak açıklamaktan kaçınmayan, genel geçer hiçbir şeyi umursamadan kendi doğrularını arayan ve söyleyen gerçek bir fikir insanı arıyorsanız, Türkiye’deki ender örneklerinden biri Celâl Şengör’dür. Bilimsel eleştiriye açıklığıyla, her ne kadar ilk bakışta bana Heidegger’i anımsatan politik duruşuyla bir “demokrat” gibi görünmese de aslında o bir bilgi demokratıdır ve eleştirel düşüncenin önemini tüm Türkiye’ye en iyi anlatan ve öğreten kişidir. Bugün elinize aldığınız bu kitap, Türkiye’nin yetiştirdiği çok yönlü ve nadide bir âlimle, bizim Karl Popper’imizle yapılmış enfes bir nehir söyleşidir. Okuyacağınız sohbet, bir bilim ve bilgi insanının çocukluktan itibaren nasıl adım adım geliştiğini ve nasıl evrildiğini anlatan bir özet, bir yolculuk öyküsüdür. Şen ve neşeli görünüşünün arkasında büyük bir ciddiyet saklayan, kendisine yapılan her türlü eleştiriyi kucaklarken bilime yapılan saygısızlığa büyük öfke duyan bir bilim insanı olarak tanıdığım Celâl Şengör’ün dediği gibi, başkalarının cehaleti nasıl bizim yaşamımızı etkiliyorsa Celâl’in bilgeliği de bizim yaşamımızı olumlu yönde etkilemiştir ve etkileyemeye devam edecektir. Bu kitap da muhtemelen bu etkinin halkalarından biri olacaktır.", AuthorId = 2, Publisher = "Masa Kitap", Language = "Türkçe", PageCount = 260, Price = 88.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "senin-cahilligin-benim-yasamimi-etkiliyor.jpg"},
                new Product(){ Name = "Aptalı Tanımak", Description = "Şu anda Türkiye’ye egemen olan cehalet yönetimi, toplum olma bilincimizde büyük yaralar açmıştır ve açmaya da devam etmektedir. Öncelikle, toplumun bir grup olarak rasyonel düşünme yeteneğini silip süpüren yobazlık ve düşünceye değil korkuya dayanan cemaat yaşamının hortlatılması, toplumsal dokumuzu derinden yaralamıştır. Buna ilaveten eğitimimizde yaratılan kargaşa ve kalitesizlik, bir toplum olarak bilgi edinme ve değerlendirme yetimizi ortadan kaldırmak üzeredir. Tüm bunları yapanların eleştirilmesine, toplumda gerçeği aramak için oluşturulabilecek bir serbest düşünce ve tartışma ortamının oluşturulmasına imkân verecek basın özgürlüğünün alenen, fütursuzca tehdit edilmesi ve buna toplumdan en ufak bir reaksiyon gelmemesi ortaya konan yıkım projesinin toplumca algılanamamasına ve dolayısıyla bertaraf edilememesine neden olmaktadır. Bahsettiğim yıkım projesi, bir grup kötü niyetli insanın Türkiye’yi ortadan kaldırma projesi olarak algılanmamalıdır. Kuşkusuz, içimizde bu yıkım projesini yönetenleri dışarıdan destekleyenlerin böyle bir amaçları olabilir ve muhtemelen vardır da. Ancak bu projeyi içimizde (ve başımızda) bulunarak yürüten ve destekleyenlerin yaptıklarının tamamen farkında olduklarını sanmıyorum. Ortaya çıkan ve benim kısaca “proje” diye betimlediğim olgu aslında yalnızca cehalet ve aptallığın ortaya çıkardığı bir süreçtir. Tarih boyunca cehaletin ve aptallığın eline geçen toplumların kaderleri hep bizimki gibi olmuştur. Zira cahil, çevresiyle temasa geçemediği gibi bizzat kendisi hakkındaki bilgileri de değerlendiremez. Aptal ise bu veriler kendisine sunulsa bile bunlarla ne yapacağını düşünemez. Cahil ve aptal her türlü eleştiriden korkar; zira bellediği yolun dışında bir yolun varlığını bilmez, olabileceğini düşünemez ve kendisine gösterilse bile değerlendiremez. Bu durumda yapabileceği tek şey, bugün Türkiye’de olduğu gibi, toplumsal terör, yani korku yaratmaktan ibaret olur.", AuthorId = 2, Publisher = "İnkılap Kitabevi", Language = "Türkçe", PageCount = 208, Price = 93.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "aptali-tanimak.jpg"},      
                new Product(){ Name = "Kürk Mantolu Madonna", Description = "Her gün, daima öğleden sonra oraya gidiyor, koridorlardaki resimlere bakıyormuş gibi ağır ağır, fakat büyük bir sabırsızlıkla asıl hedefine varmak isteyen adımlarımı zorla zapt ederek geziniyor, rastgele gözüme çarpmış gibi önünde durduğum Kürk Mantolu Madonna'yı seyre dalıyor, ta kapılar kapanıncaya kadar orada bekliyordum. Kimi tutkular rehberimiz olur yaşam boyunca. Kollarıyla bizi sarar. Sorgulamadan peşlerinden gideriz ve hiç pişman olmayacağımızı biliriz. Yapıtlarında insanların görünmeyen yüzlerini ortaya çıkaran Sabahattin Ali, bu kitabında güçlü bir tutkunun resmini çiziyor. Düzenin sildiği kişiliklere, yaşamın uçuculuğuna ve aşkın olanaksızlığına (?) dair, yanıtlanması zor sorular soruyor.", AuthorId = 4, Publisher = "Yapı Kredi Yayınları", Language = "Türkçe", PageCount = 160, Price = 13.75, Stock = 500, IsApproved = true, CategoryId = 1, Image = "kurk-mantolu-madonna.jpg"},      
                new Product(){ Name = "İçimizdeki Şeytan", Description = "İsteyip istemediğimi doğru dürüst bilmediğim, fakat neticesi aleyhime çıkarsa istemediğimi iddia ettiğim bu nevi söz ve fiillerimin daimi bir mesulünü bulmuştum: Buna içimdeki şeytan diyordum, müdafaasını üzerime almaktan korktuğum bütün hareketlerimi ona yüklüyor ve kendi suratıma tüküreceğim yerde, haksızlığa, tesadüfün cilvesine uğramış bir mazlum gibi nefsimi şefkat ve ihtimama layık görüyordum. Halbuki ne şeytanı azizim, ne şeytanı? Bu bizim gururumuzun, salaklığımızın uydurması... İçimizdeki şeytan pek de kurnazca olmayan bir kaçamak yolu... İçimizdeki şeytan yok... İçimizdeki aciz var... Tembellik var... İradesizlik, bilgisizlik ve bunların hepsinden daha korkunç bir şey: hakikatleri görmekten kaçmak itiyadı var... Bu romanında, toplumsal gündemin kişilikler üzerindeki baskısını ve güçsüz insanın kapana kısılmışlığını gösteriyor Sabahattin Ali. Aydın geçinenlerin karanlığına, insanın içindeki şeytan'a keskin bir bakış.", AuthorId = 4, Publisher ="Yapı Kredi Yayınları", Language = "Türkçe", PageCount = 267 , Price = 15.50, Stock = 500, IsApproved = true, CategoryId = 1, Image = "icimizdeki-seytan.jpg"},
                new Product(){ Name = "Sırça Köşk", Description = "Niçin hep acı şeyler yazayım? Dostlar, yufka yürekli dostlar bundan hoşlanmıyorlar. 'Hep kötü, sakat şeyleri mi göreceksin?' diyorlar. 'Hep açlardan, çıplaklardan, dertlilerden mi bahsedeceksin? Geceleri gazete satıp izmarit toplayan serseri çocuklardan; bir kaşık toprak, bir bakraç su için birbirlerini öldürenlerden; cezaevlerinde ruhları kemirile kemirile eriyip gidenlerden; doktor bulamayanlardan; hakkını alamayanlardan başka yazacak şeyler, iyi güzel şeyler kalmadı mı? Niçin yazılarındaki bütün insanların benzi soluk, yüreği kederli? Bu memlekette yüzü gülen, bahtiyar insan yok mu?", AuthorId = 4, Publisher = "Yapı Kredi Yayınları", Language = "Türkçe", PageCount = 141, Price = 15.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "sirca-kosk.jpg"},
                new Product(){ Name = "Hayvan Çiftliği", Description = "İngiliz yazar George Orwell (1903-1950), ülkemizde daha çok 1984 adlı kitabıyla tanınır. Hayvan Çiftliği, onun çağdaş klasikler arasına girmiş ikinci ünlü yapıtıdır. 1940'lardaki 'reel sosyalizm'in eleştirisi olan bu roman, dünya edebiyatında 'yergi' türünün başyapıtlarından biridir. Hayvan Çiftliği'nin kişileri hayvanlardır. George Orwell, bu romanında tarihsel bir gerçeği eleştirmektedir. Romandaki önder domuzun, düpedüz Stalin'i simgelediği açıkça görülecektir. Öbür kişiler bire bir belli olmasalar da, bir diktatörlük ortamında yer albilecek kişilerdir. Romanın alt başlığı Bir Peri Masalı'dır. Küçükleri eğlendirecek bir peri masalı değildir; ama roman, bir masal anlatımıyla yazılmıştır.", AuthorId = 5, Publisher = "Can Yayınları", Language = "Türkçe", PageCount = 152, Price = 25.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "hayvan-ciftligi.jpg"},                                               
                new Product(){ Name = "Bin Dokuz Yüz Seksen Dört - 1984", Description = "Geçmişi kontrol eden, geleceği de kontrol eder: Şimdiyi kontrol eden, geçmişi de kontrol eder. Her şey 1984 yılında geçer. Birbiriyle mütemadiyen savaşan üç büyük gücün elinde bölünmüş bir dünya, mutlak güce sahip bir Parti, kapanması yasak tele-ekranlarla her hareketi denetleyen Düşünce Polisi, her şeyi izleyen Büyük Birader ve diğer tüm düşünce biçimlerini imkânsız hâle getirmek için oluşturulan “Yenidil”. Gerçek Bakanlığı’nın altındaki Arşiv Bölümü’nün gözlerden ırak odalarında, Parti’nin ihtiyaçları-na göre geçmişi yeniden yazan Winston Smith’in oyununda arka plan bu kâbustur işte. Herkesi dilediği gibi kontrol eden bu totaliter dünyaya karşı içinde isyan tohumları büyüyen Winston, hakikat ve özgürlüğe duyduğu özlemin yanında aşka da kayıtsız kalamayacaktır. Yirminci yüzyılın en çok okunan ve en etkili kitaplarının başında gelen George Orwell’in distopik başyapıtı Bin Dokuz Yüz Seksen Dört, dönemler değişse de varlığını sürdüren tota¬liter dünya düzenine tutulmuş bir ayna olmayı sürdürüyor.", AuthorId = 5, Publisher = "Can Yayınları", Language = "Türkçe", PageCount = 296, Price = 13.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "1984.jpg"},                                             
                new Product(){ Name = "Satranç", Description = "Stefan Zweig, en çok okunan eserlerinden olan Satranç’ta, bir geminin seçkin yolcuları üzerinden toplumsal düzenin karmaşasını, bugünün geçmişin izlerini nasıl silinemez şekilde içinde sakladığını ve acımasız siyasi otoritenin yarattığı travmaların beklenmedik sonuçlarını, aklın sınırlarını zorlayan bir dönemin gerçekliği içinde anlatıyor. Satranç şampiyonu Czentovic'te, cehaletin içindeki gizli dehayı; Doktor B.'nin aklının soyut düzleminde oynadığı satrancında ise sessizce katlanılan bir acizliği görüyoruz.", AuthorId = 3, Publisher = "İş Bankası Kültür Yayınları", Language = "Türkçe", PageCount = 64, Price = 13, Stock = 500, IsApproved = true, CategoryId = 1, Image = "satranc.jpg"},
                new Product(){ Name = "Olağanüstü Bir Gece", Description = "Olağanüstü Bir Gece, Ravaruska’daki çatışmada hayatını kaybeden Friedrich Michael von R…’nin başından geçen tuhaf olaylar dizisini okuyucunun dikkatine sunuyor. Stefan Zweig’ın psikolojik tahlilleriyle kılcal damarlarına ineceğiniz hikâye, zihin akışlarıyla bezeli. Hayatta her şeye sahip birinin, nelere muhtaç olduğunu fark ettiriyor. Kitap, sadece tek bir gecede yaşanan büyülü olaylarla benliğin değişebildiğini haykırıyor. Zweig’ın tek geceye sığdırdığı bu novellası, Almanca aslından Türkçeye çevrildi.", AuthorId= 3, Publisher = "ş Bankası Kültür Yayınları", Language = "Türkçe", PageCount = 52, Price = 13.00, Stock = 500, IsApproved = true, CategoryId = 1, Image = "olaganustu-bir-gece.jpg"},
                new Product(){ Name = "Sokrates’in Savunması", Description = "Sokrates, gençleri yeni fikirlerle baştan çıkarmak ve tanrıları reddetmek suçundan yargılandı. Hayatına kastedilen M.Ö. 399’daki mahkeme, hitabet türünün ilk örneklerinden sarsıcı bir savunmaya sahne oldu. Sokrates’in savunmasını izlemeye gelen meraklı topluluk arasında, öğrencisi Platon da bulunuyordu. Bu elim hadise sonrasında Platon, özgün ruhuna dürüstçe sadık kaldığı, Sokrates’in ağzından söylettiği konuşmayla Batı felsefesinin en meşhur metnini kaleme aldı. Eser aynı zamanda, suçlayanlara karşı Sokrates’i savunmak ve savunanların inandığı gerçek Sokrates’i tanıtmak için düzenlenmiş, tarihsel arka plana sahip bir edebiyat metnidir.", AuthorId = 7, Publisher = "Kapra Yayıncılık", Language = "Türkçe", PageCount = 56, Price = 13.00, Stock = 100, IsApproved = true, CategoryId = 3, Image = "sokratesin-savunmasi.jpg"},
                new Product(){ Name = "Devlet", Description = "Platon Devlet adlı eserinde ideal devleti ve siyasal yönetim biçimini araştırır. Büyük Yunan filozofu adaletli, doğru ve güçlü bir topluluk yapısının nasıl olması gerektiğini bütün ayrıntılarıyla anlatır. Devlet, insan düşüncesinin toplumsal ve politik yaşamı aklın buyruğuna sokmak, ona ahlak ve doğruluk açısından şekil vermek için harcadığı ilk ve en köklü çabalardan biri, göz kamaştırıcı bir örneğidir.", AuthorId = 7, Publisher = "İskele Yayıncılık", Language = "Türkçe", PageCount = 223, Price = 35.00, Stock = 100, IsApproved = true, CategoryId = 3, Image = "devlet.jpg"},
                new Product(){ Name = "Yasalar", Description = "Platon, hiç kuşku yok ki düşünce tarihinin en önemli ve etkili filozoflarından biridir. Felsefenin kurumsallaşmasına ve felsefede yazılı geleneğin oluşmasına katkıda bulunmuş, iki dünyalı metafiziğiyle bütün bir Ortaçağ düşüncesini belirleyecek olan idealist felsefe geleneğinin başlatıcısı olmuştur. Hıristiyan Ortaçağ felsefesine ve İslam düşüncesine etkisi bakımından da ayrıca önem taşıyan Platon, düşünce tarihi boyunca tartışılan tüm problemleri yüzlerce yıl öncesinden ele almış ve ilk büyük felsefi sistemi inşa etmiştir. Platon’un en uzun diyaloglarından biri olan Yasalar sadece Platon’un düşüncesinde siyasi teori ve pratik arasındaki ilişkinin sorunlarını yansıtmakla kalmıyor; aynı zamanda onun aile, kadınların statüsü, mülkiyet hakları, ceza hukuku ile din ve güzel sanatların gündelik hayattaki rolü hakkındaki kapsamlı düşüncelerini de ortaya koyuyor.", AuthorId = 7, Publisher = "Say Yayınları", Language = "Türkçe", PageCount = 480, Price = 148.28, Stock = 50, IsApproved = true, CategoryId = 3, Image ="yasalar.jpg"},
                new Product(){ Name = "Bilgiyle Sohbet", Description = "Avrupa Bilimler Akademisi'nin ve Amerikan Bilimler Akademisi'nin ilk Türk üyesi, Rus Bilimler Akademisi'ne Fuat Köprülü'den sonra seçilen ikinci Türk, Türkiye Bilimler Akademisi'nin en genç kurucu üyesi, TÜBİTAK Bilim Ödülü kazanan en genç bilim adamı... İki şeref doktorası, Paris'te Collège de France'da profesörlük, ulusal ve uluslararası otuz bir adet şeref payesi ve ödül. Tüm bu nitelikleri şahsında toplayan Prof. Dr. A. M. Celâl Şengör halen İstanbul Teknik Üniversitesi Maden Fakültesi Jeoloji Mühendisliği Bölümü ile Avrasya Yer Bilimleri Enstitüsü'nde görevini sürdürmektedir. Dünyanın en saygın jeolog, bilim adamı ve üniversite hocalarından biri olmasının yanı sıra Prof. Şengör'ün en önemli özelliği hayata bir bütün olarak bilim çerçevesinden bakmasıdır. Bu anlamda kelimenin tam anlamıyla bir \"akademisyen\"dir. Prof. Şengör'ün yirmi yılı aşkın süreyle çeşitli dergi ve gazetelerde yayımlanan yazıları ve farklı platformlarda yaptığı konuşmalarının metinleri elinizdeki kitapta bir araya getirilmiştir. Prof. Şengör bilimsel birikimini elbette yine başta bilim olmak üzere eğitim, tarih, arkeoloji, coğrafya, edebiyat, toplum ve kültür gibi pek çok alanda okurlarla paylaşıyor. Herkesi Bilgiyle Sohbet'e davet ediyor.", AuthorId = 2, Publisher = "İş Bankası Kültür Yayınları", Language = "Türkçe", PageCount = 772, Price = 110.50, Stock = 75, IsApproved = true, CategoryId = 4, Image = "bilgiyle-sohbet.jpg"},
                new Product(){ Name = "Yakın Tarihin Gerçekleri", Description = "İttihatçılar milliyetperver ve büyük ideallere sahiplerdi ama kendilerini değerlendiremeyen bir ekip olmaları onları başarısızlığa sürükledi. “Mustafa Kemal (Atatürk), Suriye’de Vatan Cemiyeti’ni kuruyor, ertesi sene Makedonya’ya geliyor, oradan Trablusgarp’a koşuyor. Trablusgarp’taki görevi bitince tekrar bu tarafa Balkan Harbi’ne geliyor. Bu durum tabii ki kendisini ve düşüncelerini müthiş etkilemiştir.” Birinci Dünya Savaşı'ndan sonra Türk toplumu kaosu ve yeni bir dünya savaşını değil, Milli Mücadele'yi tercih etmiştir. Osmanlı İmparatorluğu, milliyetçi akımlar sayesinde dağılan tek imparatorluk değildi; fakat ne Rusya, ne de Avusturya-Macaristan’da ulusalcı akımlar bu derecede aktif ve silahlı eyleme dönüşmüştü. 1967'de bindiğimiz trendeki ihtiyar Araplar 'Ah nerede o Osmanlı!' diye yakınıyorlardı. Cevabı düşündürücüdür. Acaba o Osmanlı'yı kim kovaladı, bizimle beraber mi kovalandı; bilemiyoruz. 1918 yılında, mütarekenin en hazin vaktinde, millet her yerde direniyordu. Ama bu direnişlerin arasında koordinasyon yoktu. O eşgüdümü hangi politik deha sağlayacaktı? Ancak arkasında askerî bir başarı ve müspet intibaları olan bir komutan… Mustafa Kemal Atatürk... “İkinci Dünya Savaşı, cephede öldürdüklerinden çok, geride yaşayan ölüler bıraktı.”", AuthorId = 1, Publisher = "Kronik Kitap", Language = "Türkçe", PageCount = 352, Price = 69.00, Stock = 50, IsApproved = true, CategoryId = 5, Image = "yakin-tarihin-gercekleri.jpg"},
                new Product(){ Name = "Cumhuriyet'in İlk Yüzyılı 1923-2023", Description = "\"Türklerin son iki asrı bütün Doğu dünyasında ve Balkanlar'da dikkatle gözden geçirilmesi gereken büyük bir tarihî yolculuktur. Bu nedenle de Dünya Tarihi'nin önemli bir parçasıdır ve dikkatle üzerinde durulmalıdır.\"\r\nİlber Ortaylı \n“Cumhuriyet'in İlk Yüzyılı'na yeni devletimizin yapı taşlarının döşendiği Osmanlı İmparatorluğu'nun modernleşme döneminden başladık.\r\nAtatürk ve silah arkadaşlarının yetiştiği II. Abdülhamid'in modernlik arayışı içinde geçen yıllarını, ama aynı zamanda istibdad günlerini ve buna karşı isyan edip hürriyet arayan genç Osmanlı subaylarının maceraları hayatları...\r\nMillî Mücadele dönemini, özgürlük havasının egemen olduğu Cumhuriyet'in ilk iki yılını ve tek partili zorlu zamanları, ardından gelen çok partili siyasal yaşamın başladığı 1950'li yılları...\r\n1913 Babıali Baskını'yla başlayan darbeler tarihini...\r\nYeni devletin ilk gününden itibaren çözmeye çalıştığı kadim problemleri; Kürt Sorunu'nu, \"irtica\" meselesini ve eğitim konusunu...\r\nİslâmcılıktan milliyetçiliğe, merkez sağdan sosyal demokrasiye bütün siyasal akımları...\r\n1876'dan 1924'e ve 1982'ye anayasa metinlerimizi... Bizleri 2023'e taşıyacak yeni anayasa özlemimizi...\r\nAsırlık dış politikamız, ikili ilişkilerimiz, uluslararası kuruluşlardaki temsiliyetimiz, Kıbrıs Barış Harekâtı, AB macerası ve Ortadoğu politikalarımızı...\r\nŞehirleşme, üniversiteleşme, gecekondulaşma, ekonomik büyüme, yolsuzluklar, gündelik yaşamdaki nitelik ve kalite kaybı gibi en güçlü sosyolojik dinamik ve gelişmeleri...\r\nYani bizi biz yapan ve bugünlere taşıyan önemli tarihsel dinamikleri konuştuk...”\r\nİsmail Küçükkaya", AuthorId = 1, Publisher = "Kronik Kitap", Language = "Türkçe", PageCount = 304, Price = 57.00, Stock = 145, IsApproved = true, CategoryId = 5, Image = "cumhuriyetin-ilk-yuzyili.jpg"}
                
            };
            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }
            context.SaveChanges();

            base.Seed(context);
        }
    }
}